### ISSUE TITLE
like, ilike 기능 추가

### ISSUE THREAD

**Issue by westhyena** [linewalks/daqm#2]
SQL의 like, ilike  기능을 추가합니다

**Comment by yuna12** [comment]
### 11/09
**db_table 모듈의 like, ilike operator 구현**
- SQL like, ilike, not like, not ilike operator를 사용하여 구현 완료
- 테스트 pass 확인

### 11/10
**data_frame 모듈의 like, ilike operator 구현**
- Regular expression(정규표현식)을 사용하여 구현할 경우
  -  ilike: lower(string)으로 변환 후 사용
  - not like/ilke: 동일 로직에 `~` operator 사용
  - 생각한 내용
    - %는 `[\w\s]*`, _는 `.`으로 매치하자.
    - 예시:
      1. s% -> s[\w\s]*
      2. s_ -> s.$
      3. %s% -> [\w\s]*s[\w\s]*
      4. %s_ -> [\w\s]*s.$
      5.  _s% -> ^.s[\w\s]*
      6.  _s -> '^.s'
    - 이 방법의 문제: 
      1. `.`은 개행 문자 외 모든 문자와 일치하여 개행 문자 식별이 안됨
      2. `[\w\s]`은 alphanumeric, any white space와 일치하여 `.`, `!`, `#` 등 기타 특수 기호의 식별이 안됨

**Comment by yuna12** [comment]
### 11/12 (금)
* like, ilike 구현
```python
if "%" in right_col:
  right_col = right_col.replace(
    "%%",
    r"(.|\s)*"
  )
elif "_" in right_col:
  if right_col[0] == "_":
    right_col = "^" + right_col
  elif right_col[-1] == "_":
    right_col = right_col + "$"
  right_col = right_col.replace("_", r"(.|\s)")
```
%는 (.|\s)* 으로 모든 문자 또는 줄바꿈 문자 매치가 0글자 이상
_는 (.|\s)으로 모든 문자 또는 줄바꿈 문자 매치가 1글자 (_로 시작하는 경우 ^{정규표현식}, _로 끝나는 경우 {정규표현식}$으로 구현

* case sensitive
```python
res_col = left_col.str.contains(right_col)
  if col.operator == "ilike":
    res_col = left_col.str.contains(right_col, case=False)
```
contains 함수의 case(case sensitive 파라미터)로 구분

* notlike, notilike 
  * 예상 구현은 `^` 메타 문자를 사용하여 구현하고 싶은데 [^{정규표현식}]으로 사용하는 것 같은데 [.]는 메타문자가 아닌 문자그대로 .을 인식해서 [^(.|\s)] 로 될 지 모르겠다.
  * f"[^({right_col})]" 로 해봤을 때 테스트를 통과했는데, 검증을 더 해봐야 함.

**Comment by yuna12** [comment]
### 11/16 (화)

* (data_frame 모듈) not like, not ilike 구현
  - ^ (caret) 문자가 [^]으로 사용될 때 'Not follow ~'으로 동작한다고 하는데 `r"[^((.|\s)*s$)]"` 으로 `NOT LIKE %s`을 해봤을 때 검색이 잘 되지 않았음.
    - 모든 결과가 True로 나와야 하는데 False로 나옴.
  ![image](https://user-images.githubusercontent.com/12584240/141959886-883cc653-ffe2-412b-bcb9-f117d4e4439f.png)

  - X(?!Y) 같은 패턴을 사용하여 `Negative lookahead`로 not match 같은 효과를 낼 수 있다는 스택오버플로우를 참조
    -  모든 결과가 올바르게 나옴
  ![image](https://user-images.githubusercontent.com/12584240/141960192-081083ce-c029-4cfe-9848-07c0e763d08c.png)
  - 하지만, 코드로 구현했을때 결과가 다르게 나옴(모두 False로 리턴됨)
    - 코드: 
    ![image](https://user-images.githubusercontent.com/12584240/141960380-57ce1e89-1864-4112-8c7f-39a7f6305337.png)
    - right_col에 할당된 값:
    ![image](https://user-images.githubusercontent.com/12584240/141960820-dc5ff97a-37d6-4470-9311-9b0ef6df4646.png)
    - 결과: 
    ![image](https://user-images.githubusercontent.com/12584240/141960705-2f9511c3-9e40-4014-8e2c-4d123fdbf6c4.png)
