### ISSUE TITLE
[function] date_diff 함수를 사용하여 age를 구할 때 days를 years로 변환하는 방법

### ISSUE THREAD

**Issue by wnet500** [linewalks/daqm#30]
## 이슈
예시)
data_1 = "2008-01-25"
data_2 = "1959-02-01"

### 1. DAQM date_diff
결과값: 17890 (단위: day)
**year로 변환: 17890 // 365 = 49 (나누어서 몫만 취함)**

### 2. PostgreSQL
```
SELECT age(date('2008-01-25'), date('1959-02-01'))
```
결과값: 48 years 11 mons 24 days

**year만 추출**
```
SELECT
    EXTRACT ('year' from age(date('2008-01-25'), date('1959-02-01')))
```
결과값: 48

### 3. Python 실험
```
from datetime import date
from dateutil.relativedelta import relativedelta
a = (date(2008,1,25) - date(1959,2,1)).days
b = relativedelta(date(2008,1,25), date(1959,2,1))
```
a값: 17890
b값: relativedelta(years=+48, months=+11, days=+24)
a // 365 값: 49
b.years 값: 48

### 논의하고 싶은 부분
- days에서 year의 값을 추출하고 싶을 때,
단순히 days / 365한 값의 몫을 취하면 된다고 생각했으나,
다른 것 같음

## 최종 논의
- 두 date, datetime간의 차이를 (years, months, days, hours, minutes, seconds) 나타내는 time_diff 함수 구현
- time_diff, date, datetime에서 years, months, days, hours, minutes, seconds를 추출하는 extract 함수 구현

**Comment by westhyena** [comment]
단순하게 계산할 때는 `days // 365.25` 를 한다고 하더라고요.
4년에 1번은 2월이 29일까지 있어서.. 평균 365.25일이라고 잡는다고..

**Comment by wnet500** [comment]
그렇군요...
현재 DAQM의 date_diff는 결과값으로 "days"의 값을 리턴하게 되어 있는데,

- PostgreSQL에서의 age(time diff의 결과값을 years, months, days 형태로 리턴)와 extract (years, months, days를 선택하여 값을 추출) 두 함수의 새로운 구현이 필요할지

- 현재 급한대로 age를 구할 때는 time_diff값에서 365.25로 나눈 값을 사용할지

어떤 것이 좋을지 의견이 궁급합니다.

@yuna12 
@westhyena

**Comment by yuna12** [comment]
저는 365.25를 나눈 값으로 사용해서 나이를 구하면 될 것 같은데, extract 함수 구현이 필요하면 구현을 진행하면 될 것 같습니다.

**Comment by westhyena** [comment]
제 생각엔 지금 48이 나오는 것은 age의 의미와는 다른 것 같습니다.
단순히 time delta에서 year만 추출한 부분인 것 같아요

48 years 11 months 라면 반올림해서 49 years라고 보는게 더 맞지 않을까 싶기도 합니다.
365.25로 나누어서 소수점이 포함된 값을 리턴하게 하고 반올림을할지 내림할지 올림할지는 그 후의 데이터 처리 선택에 맡기는 게 좋지 않을까 생각됩니다.

**Comment by wnet500** [comment]
정우님 저는 48 years 11months라면 만나이는 48세가 맞지 않나 싶습니다.

**Comment by wnet500** [comment]
Days를 365.25로 나누고 몫을 취하는 방법을 사용해도 되나, 엄밀하게
age + extract와는 완전히 같지는 않습니다.
예시)
```
from datetime import date
from dateutil.relativedelta import relativedelta
a = (date(2008,2,1) - date(1930,2,1)).days
b = relativedelta(date(2008,2,1), date(1930,2,1))
```
a 값: 28489
b.years: 78
a // 365.25: 77

**"b.years != a // 365/25"**

**Comment by westhyena** [comment]
그런 차이를 더 상세하게 보려고 월나이를 보기도 하니까요
나이는 실제로 discrete한 값이 아닌데 그렇게 처리를 해버릴 필요가 있을까 생각이 듭니다.
이것을 어떻게 처리할지는 실제로 사용할 때 고민하면 될 것 같고
daqm에서는 고민하지 않아도 될 이슈라고 생각이 들어요

**Comment by westhyena** [comment]
라이브러리에서는 최대한 여러 사용방법을 염두에 두고 대응할 수 있게(원하는대로 바꿔서 쓸 수 있게) 해주는 방향으로 구현을 해야할 것 같습니다~

**Comment by wnet500** [comment]
넵 알겠습니다. 그러면 현재 age를 구하는 쿼리(PostgreSQL extract + age 함수 사용)를 DQAM으로 변환하고 있는 중입니다.
같은 기능을 구현하기 위해
time_diff를 사용하여 days를 구한 후, // 365.25를 하여 age를 산출하도록 하겠습니다!
